### ISSUE TITLE
关于TCP压力测试问题

### ISSUE THREAD

**Issue by upupsky** [IKende/BeetleX#10]
您好！我在使用你的工具对我的TCPServer进行测试过程中有个问题：创建1000 Client，每隔1s发送。我发送20s后，就关闭连接。针对有应答的测试模式，那么Server的消息还没来得急应答client就关闭了，这样是否也能表征出server的性能呢？谢谢

**Comment by IKende** [comment]
这个不好说，主要看涉及的业务，如果没有业务仅仅是数据回发，那的确有改进的空间。
