### ISSUE TITLE
SessionReceive 接收问题

### ISSUE THREAD

**Issue by attsion** [IKende/BeetleX#16]
TcpClient client = SocketFactory.CreateClient<TcpClient>("127.0.0.1", 9090);
                    client.Stream.ToPipeStream().WriteLine("aaaaaaaa");
                    client.Stream.Flush();
                    //System.Threading.Thread.Sleep(100);
                    client.Stream.ToPipeStream().WriteLine("bbbbbbb");
                    client.Stream.Flush();

在服务端第一次启动时，客户端连续发送两条数据必须sleep，否则服务端只能收到一条；奇怪的是在不关闭服务端的情况下，再次启动客户端即使没有sleep也能正常收到两条数据的。

**Comment by IKende** [comment]
你把服务端的代码和输出的情况贴出来才能处理

**Comment by attsion** [comment]
服务端就是使用事例中的服务端，没有变化

**Comment by IKende** [comment]
@attsion 
把代码贴一下，如果你用的是readline,这情况是client两次writeline作为一次buffer处理了，
你可以在server改成 while(tryline)

**Comment by attsion** [comment]
对确实是用的readline，但是奇怪的是后续的发送没有sleep也可以正常解析了。

**Comment by IKende** [comment]
@attsion 其实这个和sleep没关系，TCP流的问题两次writeline由对方一次receive获得了

**Comment by attsion** [comment]
好的，明白了，万分感谢
