### ISSUE TITLE
可否做成一个在netcore web下使用的Server来使用

### ISSUE THREAD

**Issue by yuzd** [IKende/BeetleX#18]
比较看重性能相比kestre优越。
但是又想用到netcore web middleware的生态。
所以请问下能否实现成一个Server来替换Kestre呢，如下：

![image](https://user-images.githubusercontent.com/16083659/57352292-8eb90000-7197-11e9-9420-d518d67df225.png)

**Comment by IKende** [comment]
有时间会了解一下，如果工作量比较大的情况就不考虑了
