### ISSUE TITLE
Host静态资源时，对于文件名包含“.”号的静态资源加载有误。

### ISSUE THREAD

**Issue by zh880702** [IKende/BeetleX#19]
“.”会被解析成“\”；
例：文件“/static/css/main.b0e5dc35.css.map” 在加载时会被解析为“/static/css/main/b0e5dc35/css.map”

**Comment by IKende** [comment]
@zh880702 
这个需要自行修改文件名，因为.net core打包资源文件时候目录也是用`.`来分割,这个程序没办法调整。
