### ISSUE TITLE
TCP/IP协议，数据包(不包含协议头)，我记得和大端小端无关吧？

### ISSUE THREAD

**Issue by yun738243875** [IKende/BeetleX#2]
TCP/IP协议，数据包(不包含协议头)，我记得和大端小端无关吧？
请教一下作者，设计这个大端小端的意义是什么呢？

**Comment by IKende** [comment]
大端小端是针对不同平台存储基础类型的方式，c#是小端，java是大端

**Comment by sgf** [comment]
大端小端 主要是 针对 数据类型的内存结构的字节顺序。
