### ISSUE TITLE
socket时，服务端把客户端T掉时，客户端能捕获吗？

### ISSUE THREAD

**Issue by RoyDongdi** [IKende/BeetleX#21]

**Comment by IKende** [comment]
暂不提供这个事件，因为组件的client断线后会重连所以没有加入这个事件。
连接事件`Connected`

**Comment by RoyDongdi** [comment]
断线重连的意思是  如果网络中断这种情况也是会自动重连的吗 ？ 
因为如果在项目中，客户端没办法判断当前链接是否断开的情况下，就必须要等待捕获异常信息才知道没有发送成功，这个过程有点长

**Comment by IKende** [comment]
@RoyDongdi 
是的，如果组件检测到网络断开是会重新连接。但你这情况在网络不好的情况连接可用性是不好判断的，因为TCP的keepalive也是需要比较长的时间，建议你通过业务ping,pong来确定连接的有效性。
