### ISSUE TITLE
PipeStream.ReadString 时是否有实现类似netty的get read相关索引规则

### ISSUE THREAD

**Issue by 491134648** [IKende/BeetleX#22]
泥水大哥好:
Stream.ToPipeStream().ReadString(4)、ReadInt()是否有实现类似netty的get read相关索引规则,比如每次readInt，索引增加是数组下标索引,下一次读取从最新位开始?

**Comment by 491134648** [comment]
类似这文章的介绍 [https://www.jianshu.com/p/3930150bf7f0](https://www.jianshu.com/p/3930150bf7f0)

**Comment by IKende** [comment]
现在的PipeStream是这样设计的，每次读取后都是偏移索引的，当buffer的偏移到层部就是回收到池。
PipeStream本质上并不是一个buffer,它是一串buffer组成，所以要类以那文章的设计相对比较因难。
最好例举一下实际业务解释场景，这样更好理解用途.
