### ISSUE TITLE
client.Read does not exist and data appears cached

### ISSUE THREAD

**Issue by samcov** [IKende/BeetleX#24]
First of all client.Read() doesn't exist, so I used client.Receive(), shown in the code below.

However, I keep getting the first thing read from the server every time, but the server is sending different data on each call.

Is there something I'm doing wrong? Do I need to clear out a buffer or something?

// send to server            
client.Stream.ToPipeStream().WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(value));
client.Stream.Flush();

// Wait for a response
var reader = client.Receive();
var ret = reader.ToPipeStream().ReadLine();
return ret;

**BTW, I use a static client, I don't get a new one each time, which worked fine in the Async version.**

**Comment by IKende** [comment]
`client.Receive`  trigger the socket receive once, if data from socket receive multiple you can
```
while(true)
{
   var reader = client.Receive();
   if(reader.reader.TryReadLine(out string line))
       return line;
}
```

**Comment by samcov** [comment]
You likely had a typo, that didn't work, but this did,

while (true)
{
	var reader = client.Receive();
	if (reader.**ToPipeStream**().TryReadLine(out string line))
	    return line;
}

Thanks for your help.
