### ISSUE TITLE
Create buffer error, maximum number of buffer pools!

### ISSUE THREAD

**Issue by goodapiyes** [IKende/BeetleX#25]
BeetleX 版本1.3.2
BeetleX demo默认设置
[11:01:40] [Error] session [::ffff:127.0.0.1]:57980@38 error receive data completed SocketError Success!@Create buffer error, maximum number of buffer pools!
   at BeetleX.Buffers.BufferPool.CreateBuffer()
   at BeetleX.Buffers.BufferPool.Pop()
   at BeetleX.TcpServer.BeginReceive(ISession session)
   at BeetleX.TcpServer.ProcessReceiveArgs(SocketAsyncEventArgs e)
   at BeetleX.TcpServer.ReceiveCompleted(SocketAsyncEventArgs e)
使用TCP_UDP_PerformanceTest测试,只开一个连接的情况下持续发送数据,一段时间后BeetleX 也报错,debug下BufferPool里的mCount计数一直累加,直到超过mMaxCount

**Comment by IKende** [comment]
这是一种设计保护，一般出现这情况是连接有大量的信息流入，但stream并没有及时read出引起对应pool的buffer损耗完，导致抛这错误。一旦连接被kill,相应的buffer会回到BufferPool中。

**Comment by goodapiyes** [comment]
> 这是一种设计保护，一般出现这情况是连接有大量的信息流入，但stream并没有及时read出引起对应pool的buffer损耗完，导致抛这错误。一旦连接被kill,相应的buffer会回到BufferPool中。

将BufferPoolSize设置到2000, 模拟1000的连接数每5秒发一次数据.十几秒后还是出现maximum number of buffer pools! 断掉所有的连接,BufferPool没有恢复. 数量为0. 再次连接直接CreateBuffer(),然后报错.

**Comment by IKende** [comment]
你设置多大都没用的，这样只会导致内存越来越大，你要看一下发送的数据是否符合服务端读取的要求，如果服务没有读取到那发多了最终也只会报这错误。

**Comment by goodapiyes** [comment]
> 你设置多大都没用的，这样只会导致内存越来越大，你要看一下发送的数据是否符合服务端读取的要求，如果服务没有读取到那发多了最终也只会报这错误。
> 
> 描述一下工具发送的内容，和服务端是如何接收的。

就是用的贵项目的winform测试工具.在博客园smark的博客下载的.
名称叫 TCP_UDP_PerformanceTest.exe.
服务端接收处理就是贴的BeetleX的demo
`    
 class Program : ServerHandlerBase
    {
        private static IServer server;

        public static void Main(string[] args)
        {
           
            server = SocketFactory.CreateTcpServer<Program>();
            //server.Options.DefaultListen.CertificateFile = "text.pfx";
            //server.Options.DefaultListen.SSL = true;
            //server.Options.DefaultListen.CertificatePassword = "123456";
            server.Open();
            Console.Write(server);
            Console.Read();
        }
        public override void SessionReceive(IServer server, SessionReceiveEventArgs e)
        {
            string name = e.Stream.ToPipeStream().ReadLine();
            Console.WriteLine(name);
            e.Session.Stream.ToPipeStream().WriteLine("hello " + name);
            e.Session.Stream.Flush();
            base.SessionReceive(server, e);
        }
    }
`

**Comment by goodapiyes** [comment]
> 你设置多大都没用的，这样只会导致内存越来越大，你要看一下发送的数据是否符合服务端读取的要求，如果服务没有读取到那发多了最终也只会报这错误。
> 
> 描述一下工具发送的内容，和服务端是如何接收的。

只是发送一段普通字符串, 如果按您说的,读取完后或者kill掉所有连接后,相应的buffer会回到BufferPool中,但我测试里BufferPool耗尽后就一直为空.并没有push进来buffer了

**Comment by goodapiyes** [comment]
> 你设置多大都没用的，这样只会导致内存越来越大，你要看一下发送的数据是否符合服务端读取的要求，如果服务没有读取到那发多了最终也只会报这错误。
> 
> 描述一下工具发送的内容，和服务端是如何接收的。

嗯,找到问题了,是我发送的数据加的\r\n被工具转义了, 服务器端用ReadLine()读取的都是null, 我不是特别清楚是不是因为老是读取null,导致buffer没有被正确的push回BufferPool

**Comment by IKende** [comment]
`ReadLine() `如果接收的数据没有`\r\n`,将没有任何数据被读取,最终导致你那情况.
