### ISSUE TITLE
Listening in the TcpClient

### ISSUE THREAD

**Issue by samcov** [IKende/BeetleX#26]
In the AsyncTcpClient, listening is via the client.DataReceive event.

I would prefer to use the **async** version, but I can't **await** for a result, if there's a way, I'd like to know.

If not, is there a way to listen for data coming from the server in the TcpClient?

**Comment by IKende** [comment]
`await AsyncTcpClient.Receive` has some problems with the current version. Plan to fix the problem next week. `TcpClient` can only be used at this time.

**Comment by samcov** [comment]
Thank you!

**Comment by IKende** [comment]
V1.3.7.2 fix async tcp client await receive problem 
Using code
```
Install-Package BeetleX -Version 1.3.7.2 
```
``` csharp
            AsyncTcpClient Client = SocketFactory.CreateClient<AsyncTcpClient>("localhost", 8080,"ikende.com");
            Client.AutoReceive = false;
            while (true)
            {
                var line = Console.ReadLine();
                var result = await Client.ReceiveFrom(s => s.WriteLine(line));
                //or
                //Client.Send(s => s.WriteLine(line));
                //result = await Client.Receive();
                Console.WriteLine(result.ReadLine());
            }
```

**Comment by samcov** [comment]
**Works perfectly!!!**

Thanks for all of your hard work!
