### ISSUE TITLE
Tcp server with 100000 users

### ISSUE THREAD

**Issue by davidop** [IKende/BeetleX#27]
First of all thank you for your contribution.  I need a tcp server capable of tolerating 100,000 connected users concurrently.  Could you give me an example based on your code?  I also need to send a response to each of the connected users

**Comment by IKende** [comment]
Default memory pool size is 100MB, supporting 10,000 in the connections,you need to set the memory pool size.
``` csharp
mServer.Options.BufferPoolMaxMemory = 1024;//1GB
```

**Comment by davidop** [comment]
Thanks for the examples. They are sending me a byte[] to the tcp server but trying to do an e.Stream.ToPipeStream().ReadLine(); in its method SessionReceive returns me null. What I can do?

**Comment by IKende** [comment]
You can using `TryReadLine` in the SessionReceive ,`ReadLine` method return data end with `\r\n`

**Comment by davidop** [comment]
> You can using `TryReadLine` in the SessionReceive ,`ReadLine` method return data end with `\r\n`

Could you give me an example?

**Comment by IKende** [comment]
if line data from socket multiple receive 
```
        public override void SessionReceive(IServer server, SessionReceiveEventArgs e)
        {
            var stream = e.Stream.ToPipeStream();
            if (stream.TryReadLine(out string line))
            {
                //enter response code              
            }
        }
```

**Comment by davidop** [comment]
internal class Program : ServerHandlerBase
    {
        private static IServer server;

        public static void Main(string[] args)
        {
            ServerOptions serverOptions = new ServerOptions();
            serverOptions.LogLevel = LogType.Error;
            serverOptions.DefaultListen.Port = 32099;
            serverOptions.DefaultListen.Host = "127.0.0.1";
            serverOptions.Statistical = false;
            serverOptions.PrivateBufferPool = true;
            serverOptions.BufferSize = 1024 * 4;
            serverOptions.PrivateBufferPool = true;
            serverOptions.MaxConnections = 100000;
            serverOptions.BufferPoolMaxMemory = 1000;

            server = SocketFactory.CreateTcpServer<Program>(serverOptions);
            server.Open();
            while (true)
            {
                Console.Write(server);
                System.Threading.Thread.Sleep(1000);
            }
        }

        public override void SessionReceive(IServer server, SessionReceiveEventArgs e)
        {
            var stream = e.Stream.ToPipeStream();
            if (stream.TryReadLine(out string line))
            {
                Console.WriteLine($"line = {line}");
            }
            Console.WriteLine($"line = {line}");
        }
    }

This is my example code, the line property is still null. I remind you that the issuer is issuing me a byte [].

**Comment by IKende** [comment]
see receive content,can read bytes 
```
            var data = new byte[e.Stream.Length];
            e.Stream.ToPipeStream().Read(data, 0, data.Length);
```
