### ISSUE TITLE
Demo 的问题

### ISSUE THREAD

**Issue by nodyang** [IKende/BeetleX#28]
private Type GetType(string typeName)
        {
            Type result;
            if (!mNameTypes.TryGetValue(typeName, out result))
            {
                if (typeName == null)
                    throw new BXException("{0} type not found!", typeName);
                result = Type.GetType(typeName);
                if (result == null)
                    throw new BXException("{0} type not found!", typeName);

                mNameTypes[typeName] = result;
            }
            return result;
        }

  这一句 是不是有点多余 
  
  if (typeName == null)
                    throw new BXException("{0} type not found!", typeName);

ConcurrentDictionary<string, Type> 好像不能把null 当key

**Comment by IKende** [comment]
对的，应该放在方法开始，错误提示要改一下。
