### ISSUE TITLE
如果客户端发送内容过大，服务端 一次接收不完，如何处理？

### ISSUE THREAD

**Issue by RocChing** [IKende/BeetleX#34]
new ServerOptions() { BufferSize = 1024000 }

这个参数BufferSize  设置完； 
怎么判断 是否接收完毕?

**Comment by IKende** [comment]
自行在事件中判断`Stream.Length`

**Comment by RocChing** [comment]
自行在事件中判断Stream.Length ; 
我的意思是 客户端 发送了 长度 100; 但是 服务端只收到 50 ; 一会又收到50 ;
怎么把 两次 合到一起;

**Comment by IKende** [comment]
Stream的数据你不read是会保留的，所以只需要在适合长度的时候read即可。

**Comment by RocChing** [comment]
明白了, BufferSize = 1024000 这个参数设置的 挺大的时候 ,服务端一次接收不完整的时候, 服务端每次收到的 length 会变 , 不知道是怎么回事;

**Comment by IKende** [comment]
BufferSize 建议不要超过8K，stream不是单buffer的，length是stream可读取长度。

**Comment by RocChing** [comment]
BufferSize  我现在设置的是 100K; 
客户端发送的数据格式 改成了
N+数据长度+数据内容
然后可以实现完整接收了

建议你参考一下 Supersocket 这个框架
https://github.com/kerryjiang/SuperSocket
![image](https://user-images.githubusercontent.com/8871373/70105246-37223a80-167b-11ea-8324-12e1b67725f5.png)

**Comment by IKende** [comment]
这个协议扩展问题，具体可以看samples，有相关示例
