### ISSUE TITLE
希望不吝赐教：tcpclient判断与server断开

### ISSUE THREAD

**Issue by yesyeey** [IKende/BeetleX#36]
我子啊用beetleX测试，AsyncTcpClient当server主动断开时(比如sessionTimeOut到期)，会接受到并关闭掉；tcpClient当server主动断开时(比如sessionTimeOut到期)，还是保持连接状态，下次发送命令才会发现与主机断开。请教下这块该怎么设计呢。当网络断开或者服务端掉线了，tcpClient获知断开。

**Comment by IKende** [comment]
组件设计是会自动重连，如果有需要可以设置Connected和Disconnected委托

**Comment by yesyeey** [comment]
是的。client的sendReceive都有connect检测，但是当server检查seeiontimeout，移除session时，client并没有获得通知，client再次send时connect还是true，会报远程主机已经关闭连接，丢失一次数据。第二次发送就正常发送了。我遇到问题是当sever关闭或，seesiontimeout，网络断开时，client知晓server已经断开了。

**Comment by IKende** [comment]
这种只能自己做ask,毕竟真实网络下socket触发disconnect的时间是不确定的

**Comment by IKende** [comment]
组件设计是会自动重连，如果有需要可以设置Connected和Disconnected委托

**Comment by yesyeey** [comment]
好的，谢谢了。
