### ISSUE TITLE
TcpClient绑定IpEndPoint端口无效

### ISSUE THREAD

**Issue by EmilyEdna** [IKende/BeetleX#37]
客户端设置：`  ClientAsnyc.LocalEndPoint = new IPEndPoint(IPAddress.Any, 9110);`
![image](https://user-images.githubusercontent.com/29139143/71576127-7f256780-2b2a-11ea-986d-0d84f8bcb7af.png)

**Comment by IKende** [comment]
Beetlex是不是最新版本，如果不是可以从Nuget上获取最新的

**Comment by EmilyEdna** [comment]
是最新的版本哦

**Comment by IKende** [comment]
你指写IP，不要用any试一下

**Comment by IKende** [comment]
https://github.com/IKende/BeetleX-Samples/tree/master/TCP.JsonFormater
这个sample加了LocalEndPoint 设置

**Comment by EmilyEdna** [comment]
好的我先看看

**Comment by EmilyEdna** [comment]
Sorry，还是无法获取到正确的IP Port
以下是我的客户端和服务器端:
![image](https://user-images.githubusercontent.com/29139143/71614544-40091c00-2be7-11ea-9bde-1b6358ea1232.png)
服务器端获取到的依然不是客户端设置的：
![image](https://user-images.githubusercontent.com/29139143/71614562-5e6f1780-2be7-11ea-96ec-b379ac1860a5.png)

**Comment by EmilyEdna** [comment]
问题已经解决
