### ISSUE TITLE
同步tcp请求时，经常只能拿到一部分响应报文，不能拿到完整的。

### ISSUE THREAD

**Issue by ich-wangxf** [IKende/BeetleX#42]

**Comment by IKende** [comment]
TCP是数据流，每次接收需要自己的协议来判断是否消息完整性。

**Comment by ich-wangxf** [comment]
client = SocketFactory.CreateClient<TcpClient>(options.Host, options.Port);
                client.TimeOut = options.TimeOut;
                client.Encoding = Encoding.GetEncoding("gbk");
                client.Stream.ToPipeStream().Write(tranMessage);
                client.Stream.Flush();
                //Thread.Sleep(1000);
                var reader = client.Receive();
                var recStr = reader.ToPipeStream().ReadToEnd();


这里我加了Thread.Sleep(1000);就能拿到完整的，不加就只能拿到部分

**Comment by IKende** [comment]
``` csharp
while(true)
{
      var reader = client.Receive();
      //判断流的数据是否满足需要
}
```

**Comment by ich-wangxf** [comment]
> ```cs
> while(true)
> {
>       var reader = client.Receive();
>       //判断流的数据是否满足需要
> }
> ```

这样写会引发异常，服务端主动关闭连接

**Comment by ich-wangxf** [comment]
> > ```cs
> > while(true)
> > {
> >       var reader = client.Receive();
> >       //判断流的数据是否满足需要
> > }
> > ```
> 
> 这样写会引发异常，服务端主动关闭连接

是否应该这样写
```cs
 var builder = new StringBuilder();
 while (client.IsConnected)
 {
     try
     {
         var s = client.Receive().ToPipeStream().ReadToEnd();

         builder.Append(s);
     }
     catch (Exception e)
     {

     }
 }          
```
