### ISSUE TITLE
跨语言的问题

### ISSUE THREAD

**Issue by hanghangz** [IKende/BeetleX#49]
你的例子中,客户端和服务端都是用的beetleX自己的来做的解析和封装.
现在我想建立一个服务端,客户端可能是各种平台各种语言的,
该用什么方式来创建.?
我一直没找到协议解析相关的. 
譬如我收到一个字节数组data,
第一个字节是header,第二个字节是功能,第三个字节表示数据长度,第4个字节到N个,表示数据等等
如是创建????

**Comment by IKende** [comment]
建议你先看一下[samples](https://github.com/IKende/BeetleX/tree/master/samples)然后再看一下`PipeStream`的方法，`PipeStream.ReadByte'和`PipeStream.Read`可以支持你的说功能

**Comment by hanghangz** [comment]
码主能这么快回复我消息,实在意外,并且所提问题得到解决.真心感谢您.
在这里,我又有另一个问题.
我用的阁下的框架架的服务端,服务端和客户端都在本地. 测试可以连通.
我把服务发布到服务器(使用的公网IP)上后,客户端在本地,测试不通.直接报[目标计算机积极拒绝]的错误.
经过反复测试,我在服务器上,如果使用原生socket和相同端口,客户端在本地是可以连通的.
所以,我不知道到底是什么地方出错了,还是您的框架对公网ip有特殊设置或者不支持呢.
再次感谢您.

**Comment by hanghangz** [comment]
不好意思.我自己找到原因了.
  tcpServer.Options.DefaultListen.Host = "127.0.0.1";
修改成
  tcpServer.Options.DefaultListen.Host = "0.0.0.0";

这个太容易被人忽略了.......
