### ISSUE TITLE
关于内存泄露问题。

### ISSUE THREAD

**Issue by xuanyuan5005** [IKende/BeetleX#55]
1，创建TCP服务
2，创建测试程序，大约10000客户端个连接，发送实时数据，
3，关闭测试程序
4，反复2-3过程，内存的增长很明显，反复次数越多，增长越明显。

**Comment by IKende** [comment]
主要.net core对于socket释放的内存时效问题这个组件暂无法接管，`BeetleX`默认只有100Mb的buffer,如果超过不无法创建连接了。

**Comment by IKende** [comment]
其实最简单的办法就是dump看一下内存是那些对像占用的，早期`BeetleX`测试内存情况也是用这手段。

**Comment by xuanyuan5005** [comment]
我跟踪内存使用状况，
修改了
 ServerOptions 的
 BufferSize = 1024 * 2;
 BufferPoolSize = 5000;

调试环境1W个客户端断开，内存恢复的很快。发布之后，在Server  2012，很难回落。我再持续跟踪。

**Comment by xuanyuan5005** [comment]
Hi IKende 首先感谢你的建议。
我做了一点细致研究。

Head Memory：当1W个连接都断开的情况下基本可以回落到之前的水准，无论反复几次。
Process Memory：基本上都是有所增长。这原因比较复杂，可能有开线程占用的栈空间以及非托管资源。

后续还需要深入研究，内存居高的原因。

**Comment by IKende** [comment]
其实没有必要在意这个,只要涨到一定程度稳定即可，可以dump看一下是不是有大量的free类型内存，大部情况都会落到这里等着回收（其实GC是会根据你的可用内存来做判断的）。

**Comment by xuanyuan5005** [comment]
Hi IKende：

感谢您的耐心解答。

我已经找到问题所在。

由于我使用 大量的 **BytesHandler**。BytesHandler，没有实现IDisposable接口，所以导致GC回收过慢。感觉内存溢出的感觉。

整个测试过程中PipeStream&BufferPool表现很优秀，才是Head Memory很平稳，值得点赞。

**Comment by xuanyuan5005** [comment]
Hi IKende：

又有一个新的问题，当1W个连接的电脑休眠，或者路由器断电等等。服务端是无法获知这些链接断开，于是就存在 1W个 **虚连接**，好像目前没看到处理**TCP**长连接场景下的 **虚连接**。

关于处理**虚连接**可以通过辅助，手段。

框架层是否考虑加入这个需求？

**Comment by xuanyuan5005** [comment]
Hi IKende：

大概由于业务问题，我比较关注大量**TCP**长连接场景，以及这个场景所产生的的问题。
我发现一个问题：

1，关于**TCP**连接，大量**虚连接**问题的处理。

      当客户端因为断电、网线被拔除等原因突然断开时，服务端没办法及时知道客户端已经断线，不能及时回收socket占用的系统资源。
      解决这个问题定义一套保持和心跳消息发送机制，保证在客户端异常断开时服务端能及时的收到通知。
      **Netty** 通过 **IdleStateHandler** 处理器

      **BeetleX**是否考虑增加对应逻辑？

       如若没有，我只能通过辅助手段解决！
      谢谢！

**Comment by xuanyuan5005** [comment]
Hi IKende：

大概由于业务问题，我比较关注大量**TCP**长连接场景，以及这个场景所产生的的问题。
我发现一个问题：

1，关于**TCP**连接，大量**虚连接**问题的处理。

      当客户端因为断电、网线被拔除等原因突然断开时，服务端没办法及时知道客户端已经断线，不能及时回收socket占用的系统资源。
      解决这个问题定义一套保持和心跳消息发送机制，保证在客户端异常断开时服务端能及时的收到通知。
      **Netty** 通过 **IdleStateHandler** 处理器

      **BeetleX**是否考虑增加对应逻辑？

       如若没有，我只能通过辅助手段解决！
      谢谢！

**Comment by IKende** [comment]
组件options里有timeout配置，不过设置了这个值后你自己要手动调用server.UpdateSession()

**Comment by xuanyuan5005** [comment]
Hi IKende：

这个我看到过相关逻辑，这里的逻辑没有和数据发送、接收时间有关系。我也阅读过TcpServer.OnDetectionHandler相关代码。

也就说没有和最后一次接收、发送数据时间有联系。

简单来说，比如最后一次接收数据时间距离现在大于60秒，没有接收的话，这个可个Session可能就存在问题。或者一个长连接大于60秒，也没有发送数据。
对于一个长连接，长时间不发送或者接受收据，大概率是有问题存在。

可能你的业务和关注点不在于此。我再想其他办法。

**Comment by IKende** [comment]
session[xxx]或session.tag可以存储你需要的信息，
http://doc.beetlex.io/#c4293a709d3d455d9f64c71d6b018731 这里有生命周期事件，
BytesHandler是实现`IWriteHandler`可以根据自己需要实现
