### ISSUE TITLE
PipeStream.Seek() or PipeStream.Position Don‘t Work

### ISSUE THREAD

**Issue by eveloki** [IKende/BeetleX#60]
目前再尝试使用IMessage的Load去反序列化的时候 会大量使用ReadUInt32 ReadByte 这种方法  
参考文档是 https://www.cnblogs.com/smark/archive/2012/05/18/2507264.html

这样可以通过一堆 read的组合循序渐进的 按照顺序读写byte数组
我如果解析失败 本质上我是想要把当前接受到的byte作为日志保存的

那么正常steam流是可以通过 Seek或者Position来设置
比如 Position=0
或者Seek(0, SeekOrigin.Begin);
但是这两种方法针对PipeStream无效  甚至针对e.Stream也无效 或者对PipeStream.Stream

然而我如果选择一开始就pipeStream.Read(thisbyte, 0, thisbyte.Length);读出整个数组
（甚至对Stream进行read）
则会导致接下来所有Read操作均告失败
并且此时 Seek或者position也是无效的 （position还会报错）

综上 希望作者能够给点思路  因为我是基于普通的Stream来考虑上述场景的 
我希望的流程是 首先反序列化  如果失败 就跳到流的最开始的位置 读取整个流 存个日志之类的

**Comment by IKende** [comment]
PipeStream直接挂载在网络buffers之上，所以`Seek`或者`Position`都是不允许。
对于TCP流来说，你说的情况按理是不可接受的；这情况说明网络数据流已经受到破坏，后续流数据已经不可靠了（正常做法都是断开连接）。
如果你们只用于调试建议是readbytes后存到你们自己的protocol stream；最简单的办法是通过设置配置`LogLevel`为`Trace`，然后在IServerHandler.log方法中记录。
