### ISSUE TITLE
Network interrupt and old connection

### ISSUE THREAD

**Issue by Rivioo** [IKende/BeetleX#62]
hi again
is there any way to close old connection in tcpserver if network client interrupt or unreachable?
when network interrupt or network unreachable old tcp is established

**Comment by IKende** [comment]
You want to auto dispose dead links caused by network problems?

**Comment by Rivioo** [comment]
Yes
If client disconnect network or disable network lan Session on server still established with no close

**Comment by Rivioo** [comment]
This problem maybe crash server if max socket reached

**Comment by IKende** [comment]
Setting the connection active timeout configuration `Options.SessionTimeOut`（unit seconds）and then call `server.UpdateSession` when the data is received .

**Comment by Rivioo** [comment]
I'll try it then notify you
Thanks again
