### ISSUE TITLE
Receive error Success BytesTransferred 0

### ISSUE THREAD

**Issue by aarani** [IKende/BeetleX#64]
I'm using this code https://github.com/aarani/TgSharp/tree/dev to connect to some tcp servers. on nearly half of my tries (running the application) socket keeps getting disconnected and giving this error (it's perfectly working on other half):

Error.Message: Receive error Success BytesTransferred 0
Error.Error.Message: The operation completed successfully.

I'm not sure if this is a BeetleX bug and can't figure out how can I fix it, sorry for low amount of information I could give about this issue.

**Comment by IKende** [comment]
This is the logging information for the component，change `Options.LogLevel` to display logging info

**Comment by aarani** [comment]
Looks like client object doesn't have LogLevel option only server one does

**Comment by IKende** [comment]
Socket to receive BytesTransferred 0 indicates the remote connection was closed, the client throws this error.

**Comment by aarani** [comment]
thanks.
