### ISSUE TITLE
是否可以补全代码注释？

### ISSUE THREAD

**Issue by staneee** [IKende/BeetleX#67]

**Comment by IKende** [comment]
正在写关于组件设计的文章，核发实现代码在文章里会有说，不过这文章暂定是收费方式提供。

**Comment by HanJunJun** [comment]
怎么收钱的，在哪里能看到文章？ @beetlex-io

**Comment by beetlex-io** [comment]
https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU5NzcwMjI2Mw==&action=getalbum&album_id=1539935825956798467&scene=173&from_msgid=2247484768&from_itemidx=1&count=3#wechat_redirect
