### ISSUE TITLE
关于 ReadBytes 的一个问题

### ISSUE THREAD

**Issue by stulzq** [IKende/BeetleX#68]
使用的是 BeetleX 的TcpClient ,创建实例的代码
````csharp
var client = SocketFactory.CreateClient<TcpClient>(_options.Host, _options.Port);
````
client的各项参数均为默认，未作修改。
在读取大数据包时，发现读取的字节数组末尾有大量的0数据（一直到末尾连续），然后解析数据错误，推断是这部分数据没有正确读取，读取的代码：
````csharp
var reader = client.Receive();
var bodyByte = reader.ReadBytes(bodyLength);
````
bodyLength 大于 20000

![image](https://user-images.githubusercontent.com/13200155/97952601-f970e900-1dd8-11eb-9780-f85e13e17880.png)

如图所示，发现了大量 0 数据。

- 已排除根据头4个字节计算包body长度不正确。
- 已排除该部分数据本身为0

RT，请问有没有解决这个问题的思路。

**Comment by IKende** [comment]
你可能对这个方法理解有些问题,ReadBytes(bodyLength)并不一定就能读取相应长度的数据，这个参数只是预计读取的长读，具体读取是多少取决于pipestream有多少数据。bodyByte.Count 才是真正读取到的数据。
所以大概代码是
``` csharp
while(true)
{
   var pipestream=  client.Receive();
  if(pipestream.length>= bodylength)
   {
          //处理你的逻辑
         break;
   }
}
```

**Comment by stulzq** [comment]
谢谢解答，我确实对这个方法理解有问题，我以为是读到我传入的长度才会返回
