### ISSUE TITLE
BeetleX可以实现MQTT吗？

### ISSUE THREAD

**Issue by fymeng2017** [IKende/BeetleX#7]
您好，请问下BeetleX可以实现MQTT高并发的应用吗

**Comment by IKende** [comment]
如果你了解MQTT那应该很容易，可以看一下samples如何操作网络数据流。
https://github.com/IKende/FastHttpApi 这个http服务也是BeetleX的基础上进行构建的

**Comment by fymeng2017** [comment]
您好，我用sample里面的例子 使用工具测试为啥在server端收不到数据呢？是发送数据格式不对 还是怎么回事。谢谢

**Comment by IKende** [comment]
那个sample ，发怎样的数据？

**Comment by fymeng2017** [comment]
Echo.Server 用你介绍的TCP/UDP服务性能测试工具  发一段utf文本，server收不到，用Echo.Client 随便发什么都可以接收到，不过好像有长度限制

**Comment by fymeng2017** [comment]
我的意思是在这里不能输出：
`public override void SessionReceive(IServer server, SessionReceiveEventArgs e)
        {
            string name = e.Stream.ToPipeStream().ReadLine();
            Console.WriteLine(name);
            e.Session.Stream.ToPipeStream().WriteLine("hello " + name);
            e.Session.Stream.Flush();
            base.SessionReceive(server, e);
        }`

**Comment by IKende** [comment]
ReadLine(),有回车符的才能read出数据

**Comment by fymeng2017** [comment]
我试试看  谢谢

**Comment by abin30** [comment]
先关注下

**Comment by Grart** [comment]
我觉得，写string 的时候可以把长度写在第一位，这样不管是读string 还是line都可以不做判断

**Comment by Grart** [comment]
WCF传string 的有一长度编码算法我觉得可以借鉴下
`
	static class Program
	{
		/// <summary>
		/// 应用程序的主入口点。
		/// </summary>
		[STAThread]
		static void Main()
		{
			int _byteCount = System.Text.Encoding.UTF8.GetByteCount("ABCDEFG");
			var _intEncodeSize = GetEncodedSize(_byteCount);
			var _intEncode = Encode(_byteCount, _intEncodeSize);
			var _dCount = Decode(_intEncode, 0, _intEncode.Length);

		}

		public static byte[] Encode(int byteCount, int size)
		{
			var bytes = new byte[size];
			var offset = 0;
			while ((byteCount & 0xffffff80L) != 0)
			{
				bytes[offset++] = (byte)((byteCount & 0x7f) | 0x80);
				byteCount = byteCount >> 7;
			}
			bytes[offset] = (byte)byteCount;
			return bytes;
		}

		public static int GetEncodedSize(int value)
		{
			int _num = 1;
			while ((value & 0xffffff80L) != 0)
			{
				_num++;
				value = value >> 7;
			}
			return _num;
		}

		public static int Decode(byte[] buffer, int offset, int size)
		{
			int num = 0;
			int value = 0;
			int index = 0;
			bool isValueDecoded = false;
			while (num < size)
			{
				int num2 = buffer[offset];
				value |= (num2 & 0x7f) << (index * 7);
				num++;
				if ((index == 4) && ((num2 & 0xf8) != 0))
				{
					throw new Exception();
				}
				index = (short)(index + 1);
				if ((num2 & 0x80) == 0)
				{
					isValueDecoded = true;
					return value;
				}
				offset++;
			}
			return value;
		}
	}`
