### ISSUE TITLE
有没有详细介绍如何使用的帮助文档？

### ISSUE THREAD

**Issue by beefsteak** [IKende/BeetleX#8]
感觉帮助文档不够全，请问以后会不会有像http://docs.supersocket.net/类似的详细使用文档？

**Comment by beefsteak** [comment]
http://docs.supersocket.net

**Comment by IKende** [comment]
主要精力还是在做FastHttpApi这一块，暂抽不出时间写文档，后面有时间会加上

**Comment by e4ky** [comment]
需要在SessionReceive中获取设备上传上来的以指定byte[]（如：new byte[]{0x0D,0x0A}）为分隔的字节数组数据。
`public override void SessionReceive(IServer server, SessionReceiveEventArgs e)
        {
            //类似于实现ReadBytes(byte[] eof)
            var data= e.Stream.ToPipeStream().ReadBytes(new byte[] { 0x0D, 0x0A });
            //.........
        }`
